name: Change Year

on: push

permissions:
    actions: write

jobs:
    change-year:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@main

            - name: Disable a workflow
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                gh workflow disable change-year.yml 
                gh workflow disable codeql-analysis.yml 
