name: 🍴 Fork initialize

on: workflow_dispatch

permissions:
    contents: write
    actions: write

jobs:
    initialize-on-fork:
        runs-on: ubuntu-latest
        # only perform if the repository is forked
        if: ${{ github.event.repository.fork }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@main

            - name: Read Repository Configuration
              run: |
                  while IFS='=' read -r key value; do
                    echo "${key}=${value}" >> $GITHUB_ENV
                  done < .github/repository.config

            - name: Replace Configuration values
              run: |
                  author_name=${{ github.actor }}
                  author_email=${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com

                  echo "${name}, ${username}, ${email}"

                  echo "${author_name}, ${author_email}"

              #   # replace Name in README.md
              #   sed -i "s/$name/${pusher_username}/g" README.md

              #   # replace Name in LICENSE
              #   sed -i "s/Pritam Kundu/${pusher_name}/g" LICENSE

              #   # # replace username in all_files
              #   # find . -type f -exec sed -i "s/warmachine028/${author_name}/g; s/${email}/${email_id}/g" {} +

            # - name: Disable workflow file
            #   env:
            #       GH_TOKEN: ${{ github.token }}
            #   run: gh workflow disable fork-initialize.yml
