name: 🍴 Fork initialize

on: workflow_dispatch

permissions:
    contents: write

jobs:
    initialize-on-fork:
        runs-on: ubuntu-latest
        # only perform if the repository is forked
        if: ${{ github.event.repository.fork }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@main

            - name: Store Owner Configuration
              run: |
                  while IFS='=' read -r key value; do
                    echo "${key}=${value}" >> $GITHUB_ENV
                  done < .github/repository.config

            - name: Store Fork Owner Configuration
              run: |
                  author_name=${{ github.actor }}
                  author_email=${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com

            - name: Replace Owner with Fork Owner
              run: |
                  find . -type f | xargs sed -i "s/${username}/${author_name}/g"
                  find . -type f | xargs sed -i "s/${email}/${author_email}/g"
                  find . -type f | xargs sed -i "s/${name}/${author_name}/g"

            - name: Disable workflow file
              env:
                  GH_TOKEN: ${{ github.token }}
              run: gh workflow disable fork-initialize.yml

            - name: Push Changes
              uses: ./.github/actions/push-changes
              with:
                  message: 'feat: fork initialised repository'
