name: 🚀 Initialize repository

on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions: write-all

jobs:
    initialize-repository:
        runs-on: ubuntu-latest
        if: ${{ !github.event.repository.is_template }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@main

            - name: Repace Template Repo name
              run: |
                  repo_name=${{ github.repository.name }}
                  capitalized_repo_name=$(echo ${repo_name//-/ } | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))} 1')
                  find . -type f -exec sed -i "s/github-super-starter-kit/${repo_name}/g; s/Github Super Starter Kit/${capitalized_repo_name}/g" {} +

            - name: Delete workflow file
              env:
                  GH_TOKEN: ${{ github.token }}
              run: gh workflow disable initialize.yml

            - name: Push Changes
              uses: ./.github/actions/push-changes
              with:
                  message: 'feat: initialised repository'
              
